### ISSUE TITLE
Lighting new portals does not create a portal; no error

### ISSUE THREAD

**Issue by SXRWahrheit** [dumptruckman/Pinapp#2]
Permissions are assigned. Config:

```
worlds:
    heavens:
        id: 155
        seed: -316548508564963630
        generator: TerrainControl
        env: Normal
```
